import { useEffect, useState } from 'react'
import { request } from '../services/apiClient'
const paths={passengers:'/passengers',bookings:'/bookings'}
const format=value=>value==null?'—':typeof value==='object'?JSON.stringify(value):String(value)
export default function ApiDirectory({entity}){
  const [rows,setRows]=useState([]),[error,setError]=useState(''),[reload,setReload]=useState(0),[search,setSearch]=useState(''),[page,setPage]=useState(1)
  useEffect(()=>{let active=true;request(paths[entity]).then(value=>{if(active){setRows(Array.isArray(value)?value:value?.content||[]);setError('')}}).catch(err=>{if(active)setError(err.message)});return()=>{active=false}},[entity,reload])
  const visible=rows.filter(row=>JSON.stringify(row).toLowerCase().includes(search.toLowerCase()))
  const keys=[...new Set(rows.flatMap(row=>Object.keys(row)))].slice(0,9)
  const pageSize=7,pages=Math.max(1,Math.ceil(visible.length/pageSize)),currentPage=Math.min(page,pages)
  const shown=visible.slice((currentPage-1)*pageSize,currentPage*pageSize)
  const statusCount=(pattern)=>rows.filter(row=>pattern.test(String(row.status||row.bookingStatus||'').toUpperCase())).length
  const summary=entity==='bookings'?[['Total bookings',rows.length],['Confirmed',statusCount(/CONFIRMED/)],['Pending',statusCount(/PENDING/)],['Cancelled',statusCount(/CANCELLED/)]]:[['Total passengers',rows.length],['Active passengers',statusCount(/ACTIVE/)],['Search results',visible.length],['Current page',currentPage]]
  const title=entity==='passengers'?'Passengers':'Passenger bookings'
  return <section className="sm-admin-page"><div className="sm-page-heading"><div><span className="sm-breadcrumb">Dashboard / {title}</span><h1>{title}</h1><p>{entity==='bookings'?'View seat bookings, cancellations and passenger records.':'View and search registered passenger profiles.'}</p></div><button className="button button-outline" type="button" onClick={()=>setReload(n=>n+1)}>Refresh</button></div><div className="sm-summary-grid">{summary.map(([label,value],i)=><div className="sm-summary-card" key={label}><span className={'sm-summary-icon sm-summary-icon-'+i}>{['▦','◉','◇','✓'][i]}</span><div><strong>{value}</strong><small>{label}</small></div></div>)}</div><div className="sm-table-card"><div className="sm-table-toolbar"><div className="sm-search-wrap"><span>⌕</span><input aria-label="Search records" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder={'Search '+title.toLowerCase()+'...'}/></div></div>{error&&<p className="auth-error" role="alert">{error}</p>}<div className="sm-table-scroll"><table className="data-table sm-refined-table"><thead><tr>{keys.map(key=><th key={key}>{key.replace(/([A-Z])/g,' $1')}</th>)}</tr></thead><tbody>{shown.map((row,i)=><tr key={row.id??i}>{keys.map(key=><td key={key}>{format(row[key])}</td>)}</tr>)}</tbody></table></div>{!visible.length&&<p className="sm-empty">No matching records.</p>}<div className="sm-table-footer"><span>Showing {visible.length?(currentPage-1)*pageSize+1:0} to {Math.min(currentPage*pageSize,visible.length)} of {visible.length} records</span><div className="sm-pagination"><button disabled={currentPage===1} onClick={()=>setPage(n=>Math.max(1,n-1))}>‹</button><span>{currentPage} / {pages}</span><button disabled={currentPage===pages} onClick={()=>setPage(n=>Math.min(pages,n+1))}>›</button></div></div></div></section>
}
