
package com.smartmove.backend.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

import java.time.LocalDateTime;

@Entity
@Table(
        name = "API_AUDIT_LOGS",
        indexes = {
                @Index(
                        name = "IDX_AUDIT_ACTOR",
                        columnList = "ACTOR_ACCOUNT_ID"
                ),
                @Index(
                        name = "IDX_AUDIT_ACTION",
                        columnList = "ACTION"
                ),
                @Index(
                        name = "IDX_AUDIT_ENTITY",
                        columnList = "ENTITY_TYPE, ENTITY_ID"
                ),
                @Index(
                        name = "IDX_AUDIT_CREATED",
                        columnList = "CREATED_AT"
                ),
                @Index(
                        name = "IDX_AUDIT_RESULT",
                        columnList = "RESULT"
                )
        }
)
public class ApiAuditLog {

    // ==========================================
    // PRIMARY KEY
    // ==========================================

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "ID")
    private Long id;

    // ==========================================
    // ACCOUNT PERFORMING THE ACTION
    // ==========================================

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ACTOR_ACCOUNT_ID")
    private UserAccount actor;

    // Snapshot of the username at action time.
    // This remains available even if the account
    // is subsequently renamed.
    @Column(
            name = "ACTOR_USERNAME",
            length = 150
    )
    private String actorUsername;

    @Column(
            name = "ACTOR_ROLE",
            length = 30
    )
    private String actorRole;

    // ==========================================
    // ACTION DETAILS
    // ==========================================

    // CREATE, UPDATE, DELETE, APPROVE, REJECT,
    // ASSIGN, CANCEL, LOGIN, LOGOUT, STATUS_CHANGE,
    // PASSWORD_RESET, REFUND, VERIFY, PUBLISH, OTHER
    @Column(
            name = "ACTION",
            nullable = false,
            length = 40
    )
    private String action;

    // USER_ACCOUNT, PASSENGER, DRIVER, VEHICLE,
    // ROUTE, ROUTE_STOP, TRIP, BOOKING, PAYMENT,
    // MAINTENANCE, STAFF_TRANSPORT_REQUEST,
    // ON_DEMAND_TRIP_REQUEST, ANNOUNCEMENT,
    // VEHICLE_DOCUMENT, FEEDBACK, OTHER
    @Column(
            name = "ENTITY_TYPE",
            nullable = false,
            length = 80
    )
    private String entityType;

    // String supports both Oracle numeric IDs
    // and MongoDB document IDs.
    @Column(
            name = "ENTITY_ID",
            length = 120
    )
    private String entityId;

    // ==========================================
    // RESULT
    // ==========================================

    // SUCCESS, FAILURE, DENIED
    @Column(
            name = "RESULT",
            nullable = false,
            length = 20
    )
    private String result = "SUCCESS";

    // HTTP status associated with the operation,
    // if the audit was generated by an API request.
    @Column(name = "HTTP_STATUS")
    private Integer httpStatus;

    // ==========================================
    // CHANGE SUMMARY
    // ==========================================

    @Column(
            name = "DESCRIPTION",
            length = 2000
    )
    private String description;

    @Column(
            name = "OLD_STATUS",
            length = 100
    )
    private String oldStatus;

    @Column(
            name = "NEW_STATUS",
            length = 100
    )
    private String newStatus;

    // ==========================================
    // REQUEST INFORMATION
    // ==========================================

    @Column(
            name = "HTTP_METHOD",
            length = 10
    )
    private String httpMethod;

    @Column(
            name = "REQUEST_PATH",
            length = 500
    )
    private String requestPath;

    @Column(
            name = "IP_ADDRESS",
            length = 45
    )
    private String ipAddress;

    @Column(
            name = "USER_AGENT",
            length = 500
    )
    private String userAgent;

    @Column(
            name = "CORRELATION_ID",
            length = 100
    )
    private String correlationId;

    // ==========================================
    // AUDIT TIMESTAMP
    // ==========================================

    @Column(
            name = "CREATED_AT",
            nullable = false,
            updatable = false
    )
    private LocalDateTime createdAt;

    // ==========================================
    // CONSTRUCTORS
    // ==========================================

    public ApiAuditLog() {
    }

    // ==========================================
    // JPA LIFECYCLE
    // ==========================================

    @PrePersist
    public void onCreate() {

        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }

        if (result == null || result.isBlank()) {
            result = "SUCCESS";
        }

        if (action != null) {
            action = action.trim().toUpperCase();
        }

        if (entityType != null) {
            entityType = entityType.trim().toUpperCase();
        }

        if (result != null) {
            result = result.trim().toUpperCase();
        }
    }

    // ==========================================
    // GETTERS AND SETTERS
    // ==========================================

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public UserAccount getActor() {
        return actor;
    }

    public void setActor(UserAccount actor) {
        this.actor = actor;
    }

    public String getActorUsername() {
        return actorUsername;
    }

    public void setActorUsername(String actorUsername) {
        this.actorUsername = actorUsername;
    }

    public String getActorRole() {
        return actorRole;
    }

    public void setActorRole(String actorRole) {
        this.actorRole = actorRole;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getEntityType() {
        return entityType;
    }

    public void setEntityType(String entityType) {
        this.entityType = entityType;
    }

    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public Integer getHttpStatus() {
        return httpStatus;
    }

    public void setHttpStatus(Integer httpStatus) {
        this.httpStatus = httpStatus;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getOldStatus() {
        return oldStatus;
    }

    public void setOldStatus(String oldStatus) {
        this.oldStatus = oldStatus;
    }

    public String getNewStatus() {
        return newStatus;
    }

    public void setNewStatus(String newStatus) {
        this.newStatus = newStatus;
    }

    public String getHttpMethod() {
        return httpMethod;
    }

    public void setHttpMethod(String httpMethod) {
        this.httpMethod = httpMethod;
    }

    public String getRequestPath() {
        return requestPath;
    }

    public void setRequestPath(String requestPath) {
        this.requestPath = requestPath;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getUserAgent() {
        return userAgent;
    }

    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }

    public String getCorrelationId() {
        return correlationId;
    }

    public void setCorrelationId(String correlationId) {
        this.correlationId = correlationId;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
