import { useEffect, useState } from 'react'
import MapPicker from '../../components/MapPicker'
import './smartmove-journey.css'
import { request } from '../../services/apiClient'
export default function ApiCustomTripRequests(){
 const [form,setForm]=useState({pickupAddress:'',pickupLatitude:'',pickupLongitude:'',destinationAddress:'',destinationLatitude:'',destinationLongitude:'',requestedPickupTime:'',passengerCount:1,serviceType:'CUSTOM',specialRequirements:''})
 const [pickup,setPickup]=useState(null),[destination,setDestination]=useState(null),[pickTarget,setPickTarget]=useState('pickup')
 const [rows,setRows]=useState([]),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[filter,setFilter]=useState('ALL'),[selected,setSelected]=useState(null)
 useEffect(()=>{request('/on-demand/my-requests').then(setRows).catch(e=>setError(e.message))},[refresh])
 const submit=async e=>{e.preventDefault();if(!pickup||!destination){setError('Select both map locations.');return}try{await request('/on-demand/requests',{method:'POST',body:JSON.stringify({...form,pickupAddress:pickup.label||'Pickup',pickupLatitude:pickup.latitude,pickupLongitude:pickup.longitude,destinationAddress:destination.label||'Destination',destinationLatitude:destination.latitude,destinationLongitude:destination.longitude,passengerCount:Number(form.passengerCount)})});setRefresh(n=>n+1)}catch(err){setError(err.message)}}
 return <div className="sm-custom-page">
 <header className="sm-custom-header"><div><span className="sm-eyebrow">SMARTMOVE PASSENGER</span><h1>Custom trip request</h1><p>Plan a personalised journey anywhere in Sri Lanka. Choose your pickup, destination, preferred time and seats. Our team will arrange transport after reviewing your request.</p></div><span className="sm-help">How custom trips work: Request → Review → Assignment</span></header>
 <div className="sm-custom-grid"><form className="sm-surface sm-custom-form" onSubmit={submit}>
 <h2>Trip details</h2><p>Select your pickup and destination on the map or search below.</p>
 <div className="sm-fields"><label>Pickup location<input readOnly value={pickup?.label||''} placeholder="Choose pickup on map" onClick={()=>setPickTarget('pickup')}/></label><label>Destination<input readOnly value={destination?.label||''} placeholder="Choose destination on map" onClick={()=>setPickTarget('destination')}/></label><label>Preferred date and time<input type="datetime-local" required value={form.requestedPickupTime} onChange={e=>setForm(v=>({...v,requestedPickupTime:e.target.value}))}/></label><label>Number of seats<input type="number" required min="1" max="1000" value={form.passengerCount} onChange={e=>setForm(v=>({...v,passengerCount:e.target.value}))}/></label></div>
 <div className="sm-map-container"><MapPicker pickup={pickup} destination={destination} onPickupChange={setPickup} onDestinationChange={setDestination} pickTarget={pickTarget} onTargetChange={setPickTarget} height={340}/></div>
 <label className="sm-special">Special requirements (optional)<textarea rows="3" maxLength="300" placeholder="e.g. extra luggage, child seats, multiple stops..." value={form.specialRequirements} onChange={e=>setForm(v=>({...v,specialRequirements:e.target.value}))}/></label>
 {error&&<p className="auth-error" role="alert">{error}</p>}<button className="button button-primary sm-submit">Submit custom trip request</button></form>
 <aside className="sm-surface sm-summary"><h2>Request summary</h2><div className="sm-summary-route"><small>Pickup</small><strong>{pickup?.label||'Not selected'}</strong><small>Destination</small><strong>{destination?.label||'Not selected'}</strong></div><div className="sm-summary-row"><small>Preferred time</small><strong>{form.requestedPickupTime?.replace('T',' ')||'Not selected'}</strong></div><div className="sm-summary-row"><small>Seats</small><strong>{form.passengerCount}</strong></div><div className="sm-summary-row"><small>Special requirements</small><strong>{form.specialRequirements||'None'}</strong></div></aside></div>
 <section className="sm-surface sm-requests"><h2>My custom trip requests</h2><p>View the status of your custom trip requests.</p><div className="sm-filter-tabs">{['ALL','PENDING','APPROVED','REJECTED','CANCELLED'].map(status=><button key={status} type="button" className={filter===status?'selected':''} onClick={()=>setFilter(status)}>{status==='ALL'?'All':status.toLowerCase()} ({rows.filter(r=>status==='ALL'||String(r.status).toUpperCase()===status).length})</button>)}</div><div className="sm-table-scroll"><table className="sm-table"><thead><tr><th>Request ID</th><th>Route</th><th>Date & time</th><th>Seats</th><th>Special requirements</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.filter(r=>filter==='ALL'||String(r.status).toUpperCase()===filter).map(row=><tr key={row.id}><td>CR-{row.id}</td><td>{row.pickupAddress} → {row.destinationAddress}</td><td>{String(row.requestedPickupTime||'').replace('T',' ').slice(0,16)}</td><td>{row.passengerCount}</td><td>{row.specialRequirements||'—'}</td><td><span className={'sm-status sm-'+String(row.status).toLowerCase()}>{row.status}</span></td><td><button type="button" className="sm-view" onClick={()=>setSelected(row)}>View</button></td></tr>)}</tbody></table></div>{selected&&<div className="sm-request-detail"><button className="sm-view" type="button" onClick={()=>setSelected(null)}>Close</button><h3>Request #{selected.id}</h3><p>{selected.pickupAddress} → {selected.destinationAddress} · {selected.passengerCount} seats · {selected.status}</p>{selected.assignedTripId&&<p>Assigned trip #{selected.assignedTripId}</p>}</div>}</section></div>
}
