import { Link, useParams } from 'react-router-dom'
import { ArrowRight, BusFront, ShieldCheck, Users } from 'lucide-react'
import { useAppData } from '../../services/useAppData'
import { formatDate, formatLkr } from '../../services/formatters'
import MapPicker from '../../components/MapPicker'

const today=()=>new Date().toISOString().slice(0,10)
const booked=(data,id)=>(data.bookings||[]).filter(booking=>booking.tripId===id&&booking.status!=='Cancelled').reduce((sum,booking)=>sum+Number(booking.seats||0),0)
export default function TripDetailsPage(){
  const {tripId}=useParams(),{data}=useAppData(),trip=data.trips.find(item=>item.id===tripId)
  if(!trip)return <div className="portal-empty"><span><BusFront size={22}/></span><strong>Journey not found</strong><p>This trip may have been removed from the demo schedule.</p><Link className="button button-primary" to="/passenger/search">Browse trips</Link></div>
  const route=data.routes.find(item=>item.id===trip.routeId),vehicle=data.vehicles.find(item=>item.id===trip.vehicleId),driver=data.drivers.find(item=>item.id===trip.driverId),stops=(route?.stops||[]).slice().sort((a,b)=>a.stopOrder-b.stopOrder)
  const remaining=Math.max(0,(trip.seats||0)-booked(data,trip.id)),eligible=trip.status==='Scheduled'&&trip.date>=today()&&remaining>0
  return <><Link className="portal-back-link" to="/passenger/search">← Back to route search</Link><div className="trip-detail-hero"><span>COMMUTER SERVICE · DEMO SCHEDULE</span><h1>{route?.origin}<i>to</i>{route?.destination}</h1><p>{route?.distance} km · scheduled journey · intermediate times are shown only where supplied.</p></div><div className="trip-detail-grid"><div className="trip-detail-main"><section className="portal-panel"><div className="portal-panel-head"><div><h2>Boarding and stop times</h2><p>Board before your selected destination; intermediate stops follow the route direction.</p></div></div><ol className="passenger-route-stop-list">{stops.length?stops.map(stop=><li key={stop.stopOrder}><span className="route-stop-index">{stop.stopOrder}</span><span><strong>{stop.name}</strong><small>{stop.scheduledTime||'Scheduled time not supplied'}</small></span></li>):<li><span className="route-stop-index">•</span><span><strong>{route?.origin} → {route?.destination}</strong><small>No intermediate stop timetable supplied.</small></span></li>}</ol></section><section className="portal-panel"><div className="portal-panel-head"><div><h2>Route map</h2><p>Route stop landmarks from the demo route catalogue; not vehicle tracking.</p></div></div><MapPicker routeStops={stops} readOnly showCurrentLocation={false} height={300}/></section><section className="portal-panel"><div className="portal-panel-head"><div><h2>Assigned service</h2><p>Vehicle and driver linked to this scheduled trip.</p></div></div><div className="trip-detail-facts"><div><BusFront size={17}/><span><small>VEHICLE</small><strong>{vehicle?.name||'Not assigned'}</strong><em>{vehicle?.plate} · {vehicle?.type}</em></span></div><div><Users size={17}/><span><small>DRIVER</small><strong>{driver?.name||'Not assigned'}</strong><em>Profile data from the demo schedule</em></span></div><div><Users size={17}/><span><small>SEATS</small><strong>{remaining} available</strong><em>{trip.seats} total seats</em></span></div></div></section></div><aside className="trip-fare-card"><span>TRIP SUMMARY</span><strong>{formatLkr(route?.fare)}</strong><small>per seat · demo fare only</small><hr/><div><span>Travel date</span><b>{formatDate(trip.date)}</b></div><div><span>Departure</span><b>{trip.departure}</b></div><div><span>Expected arrival</span><b>{trip.arrival||'Not supplied'}</b></div><div><span>Available seats</span><b>{remaining}</b></div>{eligible?<Link className="button button-primary" to={`/passenger/book/${trip.id}`}>Book this trip <ArrowRight size={15}/></Link>:<span className="trip-unavailable-note">This scheduled trip is not currently bookable.</span>}<p><ShieldCheck size={14}/> Demo booking only. No payment is collected.</p></aside></div><p className="portal-demo-caption">Route stop and schedule data are demo fixtures. Map points indicate supported stops only; no current vehicle position is implied.</p></>
}
