import { useAppData } from '../services/useAppData'
import { formatDate, formatLkr } from '../services/formatters'
import StatCard from '../components/StatCard'
import DataTable from '../components/DataTable'
import { BusFront, TicketCheck, Wallet, Users, ArrowRight, Clock3, MapPin, CircleCheck, Wrench, CalendarDays } from 'lucide-react'
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import { Link } from 'react-router-dom'

const lkrTick = value => Number(value).toLocaleString('en-LK')

export default function Dashboard() {
  const { data, currentUser } = useAppData()
  const admin = data.admins.find(profile => profile.id === currentUser?.linkedProfileId)
  const adminFirstName = admin?.name?.split(' ')[0] || 'Administrator'
  const today = new Date().toISOString().slice(0, 10)
  const month = today.slice(0, 7)
  const monthLabel = new Date(`${month}-01T00:00:00`).toLocaleDateString('en-LK', { month: 'long', year: 'numeric' })
  const paid = data.payments.filter(payment => payment.status === 'Paid' && payment.date?.startsWith(month)).reduce((total, payment) => total + Number(payment.amount || 0), 0)
  const todayTrips = data.trips.filter(trip => trip.date === today && trip.status !== 'Cancelled')
  const todayBookings = data.bookings.filter(booking => booking.bookedAt === today && booking.status !== 'Cancelled').length
  const upcoming = data.trips.filter(trip => trip.status === 'Scheduled' && trip.date >= today).sort((a, b) => a.date.localeCompare(b.date) || a.departure.localeCompare(b.departure)).slice(0, 4)
  const revenueData = Array.from({ length: 6 }, (_, index) => {
    const date = new Date()
    date.setDate(1)
    date.setMonth(date.getMonth() - (5 - index))
    const key = date.toISOString().slice(0, 7)
    return { month: date.toLocaleDateString('en-LK', { month: 'short' }), revenue: data.payments.filter(payment => payment.status === 'Paid' && payment.date?.startsWith(key)).reduce((sum, payment) => sum + Number(payment.amount || 0), 0) }
  })
  const tripData = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map((day, index) => ({ day, trips: data.trips.filter(trip => new Date(`${trip.date}T00:00:00`).getDay() === (index + 1) % 7 && trip.status !== 'Cancelled').length }))
  return <div className="page-content dashboard-page"><div className="page-heading dashboard-heading"><div><div className="eyebrow">{new Date(`${today}T00:00:00`).toLocaleDateString('en-LK',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase()} <span className="live-dot" /></div><h1>Good morning, {adminFirstName} <span className="wave">✦</span></h1><p>Here’s what’s happening across your transport network today.</p></div><div className="heading-actions"><button className="button button-outline" onClick={() => window.print()}><CalendarDays size={16} /> This week <span>⌄</span></button><Link to="/admin/trips" className="button button-primary"><PlusIcon /> Schedule a trip</Link></div></div>
    <div className="stat-grid"><StatCard label="Total vehicles" value={data.vehicles.length} change="Demo" icon={BusFront} tone="sage" hint="fleet records"/><StatCard label="Bookings today" value={todayBookings} change="Demo" icon={TicketCheck} tone="blue" hint="bookings created today"/><StatCard label="Recorded revenue" value={formatLkr(paid)} change="Demo" icon={Wallet} tone="gold" hint={monthLabel}/><StatCard label="Passenger profiles" value={data.passengers.length} change="Demo" icon={Users} tone="rose" hint="in this workspace"/></div>
    <div className="chart-grid"><section className="panel revenue-panel"><div className="panel-header"><div><h2>Recorded payments</h2><p>Paid administrative records by month</p></div><div className="chart-legend"><span /> Recorded LKR</div></div><div className="chart-total">{formatLkr(paid)} <span className="chart-subtitle">{monthLabel}</span></div><div className="chart-subtitle">Based on records marked Paid; not processed payments</div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueData} margin={{ top: 16, right: 8, left: 0, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#648d73" stopOpacity={0.2}/><stop offset="95%" stopColor="#648d73" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0eb"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 12 }} dy={10}/><YAxis axisLine={false} tickLine={false} tickFormatter={lkrTick} tick={{ fill: '#879187', fontSize: 11 }} width={45}/><Tooltip formatter={value => [formatLkr(value), 'Recorded'] } contentStyle={{ border: '1px solid #e8ece6', borderRadius: 10, boxShadow: '0 6px 20px #1c301211' }}/><Area type="monotone" dataKey="revenue" stroke="#668f75" strokeWidth={2.5} fill="url(#revenueFill)" activeDot={{ r: 5, fill: '#426d52', stroke: '#fff', strokeWidth: 2 }}/></AreaChart></ResponsiveContainer></div><div className="chart-period">Last six months · shared demo records</div></section>
      <section className="panel trips-panel"><div className="panel-header"><div><h2>Scheduled trip activity</h2><p>Trips in the shared demo schedule by weekday</p></div><Link className="text-link" to="/admin/trips">View trips <ArrowRight size={13}/></Link></div><div className="activity-summary"><strong>{data.trips.filter(trip=>trip.status!=='Cancelled').length}</strong><span>trip records in this workspace</span></div><div className="chart-area bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={tripData} margin={{ top: 14, right: 0, left: -26, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edf0eb"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 11 }} dy={9}/><YAxis axisLine={false} tickLine={false} allowDecimals={false} tick={{ fill: '#879187', fontSize: 11 }} /><Tooltip cursor={{ fill: '#f5f7f3' }} contentStyle={{ border: '1px solid #e8ece6', borderRadius: 10 }}/><Bar dataKey="trips" fill="#779681" radius={[5,5,1,1]} maxBarSize={27}/></BarChart></ResponsiveContainer></div></section></div>
    <div className="dashboard-lower"><section className="panel bookings-panel"><div className="panel-header"><div><h2>Recent bookings</h2><p>Latest passenger reservations</p></div><Link to="/admin/bookings" className="text-link">View all <ArrowRight size={14}/></Link></div><DataTable data={data.bookings.slice(0, 4)} collections={data} columns={ [['id','Booking'],['passengerId','Passenger'],['tripId','Trip'],['amount','Amount'],['status','Status']] } /></section><section className="panel upcoming-panel"><div className="panel-header"><div><h2>Upcoming trips</h2><p>Next departures in your network</p></div><Link to="/admin/trips" className="text-link">View all <ArrowRight size={14}/></Link></div><div className="trip-list">{upcoming.length ? upcoming.map(trip => { const route=data.routes.find(item=>item.id===trip.routeId);const vehicle=data.vehicles.find(item=>item.id===trip.vehicleId);const driver=data.drivers.find(item=>item.id===trip.driverId);return <div className="trip-item" key={trip.id}><div className="trip-time"><strong>{trip.departure}</strong><span>{formatDate(trip.date)}</span></div><div className="trip-route"><strong>{route?.origin} <span>→</span> {route?.destination}</strong><span><BusFront size={13}/> {vehicle?.plate} <i/> {driver?.name}</span></div><span className="trip-state"><span/>Scheduled</span></div>}) : <div className="empty-small">No upcoming trips scheduled.</div>}</div><Link className="schedule-link" to="/admin/trips"><PlusIcon /> Schedule another trip <ArrowRight size={15}/></Link></section></div>
    <section className="ops-strip"><div className="ops-title"><div className="ops-icon"><Clock3 size={18}/></div><div><strong>Operations at a glance</strong><span>Snapshot from shared demo records</span></div></div><div className="ops-metric"><span>Trips today</span><strong><MapPin size={15}/>{todayTrips.length}</strong></div><div className="ops-metric"><span>Bookings today</span><strong className="text-green"><CircleCheck size={15}/>{todayBookings}</strong></div><div className="ops-metric"><span>Fleet availability</span><strong><BusFront size={15}/>{data.vehicles.filter(v=>v.status==='Active').length}/{data.vehicles.length}</strong></div><div className="ops-metric"><span>Service alerts</span><Link to="/admin/maintenance" className="alert-metric"><Wrench size={15}/>{data.maintenance.filter(m=>m.status!=='Completed').length} open</Link></div></section>
  </div>
}
function PlusIcon(){return <span className="plus-symbol">＋</span>}
