import { useAppData } from '../services/useAppData'
import { formatLkr } from '../services/formatters'
import StatCard from '../components/StatCard'
import DataTable from '../components/DataTable'
import { BusFront, TicketCheck, Wallet, Users, ArrowRight, Clock3, MapPin, CircleCheck, Wrench, CalendarDays } from 'lucide-react'
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
import { Link } from 'react-router-dom'

const revenueData = [{ month: 'May', revenue: 132 }, { month: 'Jun', revenue: 158 }, { month: 'Jul', revenue: 151 }, { month: 'Aug', revenue: 184 }, { month: 'Sep', revenue: 198 }, { month: 'Oct', revenue: 221 }]
const tripData = [{ day: 'Mon', trips: 28 }, { day: 'Tue', trips: 34 }, { day: 'Wed', trips: 31 }, { day: 'Thu', trips: 42 }, { day: 'Fri', trips: 48 }, { day: 'Sat', trips: 55 }, { day: 'Sun', trips: 37 }]
const lkrTick = value => `${Number(value).toLocaleString()}k`

export default function Dashboard() {
  const { data } = useAppData()
  const paid = data.payments.filter(payment => payment.status === 'Paid').reduce((total, payment) => total + Number(payment.amount || 0), 0)
  const todayTrips = data.trips.filter(trip => trip.date === '2025-10-24' && trip.status !== 'Cancelled')
  const upcoming = data.trips.filter(trip => trip.status === 'Scheduled').slice(0, 4)
  return <div className="page-content dashboard-page"><div className="page-heading dashboard-heading"><div><div className="eyebrow">FRIDAY, OCTOBER 24, 2025 <span className="live-dot" /></div><h1>Good morning, Amara <span className="wave">✦</span></h1><p>Here’s what’s happening across your transport network today.</p></div><div className="heading-actions"><button className="button button-outline" onClick={() => window.print()}><CalendarDays size={16} /> This week <span>⌄</span></button><Link to="/trips" className="button button-primary"><PlusIcon /> Schedule a trip</Link></div></div>
    <div className="stat-grid"><StatCard label="Total vehicles" value={data.vehicles.length} change="8.2%" icon={BusFront} tone="sage" hint="vs last month"/><StatCard label="Bookings today" value={todayTrips.reduce((sum, trip) => sum + data.bookings.filter(b => b.tripId === trip.id && b.status === 'Confirmed').length, 0) + 42} change="12.4%" icon={TicketCheck} tone="blue" hint="vs yesterday"/><StatCard label="Revenue this month" value={formatLkr(paid * 31)} change="6.8%" icon={Wallet} tone="gold" hint="vs last month"/><StatCard label="Active passengers" value="2,840" change="4.2%" icon={Users} tone="rose" hint="vs last month"/></div>
    <div className="chart-grid"><section className="panel revenue-panel"><div className="panel-header"><div><h2>Revenue overview</h2><p>Monthly revenue across all routes</p></div><div className="chart-legend"><span /> Revenue <button aria-label="Chart options">···</button></div></div><div className="chart-total">{formatLkr(paid * 31)} <span className="trend positive">↗ 6.8%</span></div><div className="chart-subtitle">Revenue · LKR</div><div className="chart-area"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueData} margin={{ top: 16, right: 8, left: 0, bottom: 0 }}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#648d73" stopOpacity={0.2}/><stop offset="95%" stopColor="#648d73" stopOpacity={0.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#edf0eb"/><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 12 }} dy={10}/><YAxis axisLine={false} tickLine={false} tickFormatter={lkrTick} tick={{ fill: '#879187', fontSize: 11 }} width={39}/><Tooltip formatter={value => [`LKR ${value.toLocaleString()}k`, 'Revenue']} contentStyle={{ border: '1px solid #e8ece6', borderRadius: 10, boxShadow: '0 6px 20px #1c301211' }}/><Area type="monotone" dataKey="revenue" stroke="#668f75" strokeWidth={2.5} fill="url(#revenueFill)" activeDot={{ r: 5, fill: '#426d52', stroke: '#fff', strokeWidth: 2 }}/></AreaChart></ResponsiveContainer></div><div className="chart-period">May — October 2025</div></section>
      <section className="panel trips-panel"><div className="panel-header"><div><h2>Weekly trip activity</h2><p>Completed trips by day</p></div><button className="more-button" aria-label="More options">···</button></div><div className="activity-summary"><strong>275</strong><span>trips this week <em>↗ 8.1%</em></span></div><div className="chart-area bar-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={tripData} margin={{ top: 14, right: 0, left: -26, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edf0eb"/><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 11 }} dy={9}/><YAxis axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 11 }} /><Tooltip cursor={{ fill: '#f5f7f3' }} contentStyle={{ border: '1px solid #e8ece6', borderRadius: 10 }}/><Bar dataKey="trips" fill="#779681" radius={[5,5,1,1]} maxBarSize={27}/></BarChart></ResponsiveContainer></div></section></div>
    <div className="dashboard-lower"><section className="panel bookings-panel"><div className="panel-header"><div><h2>Recent bookings</h2><p>Your latest passenger reservations</p></div><Link to="/bookings" className="text-link">View all <ArrowRight size={14}/></Link></div><DataTable data={data.bookings.slice(0, 4)} collections={data} columns={ [['id','Booking'],['passengerId','Passenger'],['tripId','Trip'],['amount','Amount'],['status','Status']] } /></section><section className="panel upcoming-panel"><div className="panel-header"><div><h2>Upcoming trips</h2><p>Next departures in your network</p></div><Link to="/trips" className="text-link">View all <ArrowRight size={14}/></Link></div><div className="trip-list">{upcoming.length ? upcoming.map(trip => { const route=data.routes.find(item=>item.id===trip.routeId);const vehicle=data.vehicles.find(item=>item.id===trip.vehicleId);const driver=data.drivers.find(item=>item.id===trip.driverId);return <div className="trip-item" key={trip.id}><div className="trip-time"><strong>{trip.departure}</strong><span>{trip.date === '2025-10-24' ? 'Today' : 'Tomorrow'}</span></div><div className="trip-route"><strong>{route?.origin} <span>→</span> {route?.destination}</strong><span><BusFront size={13}/> {vehicle?.plate} <i/> {driver?.name}</span></div><span className="trip-state"><span/>Scheduled</span></div>}) : <div className="empty-small">No upcoming trips scheduled.</div>}</div><Link className="schedule-link" to="/trips"><PlusIcon /> Schedule another trip <ArrowRight size={15}/></Link></section></div>
    <section className="ops-strip"><div className="ops-title"><div className="ops-icon"><Clock3 size={18}/></div><div><strong>Operations at a glance</strong><span>Live snapshot of today's activity</span></div></div><div className="ops-metric"><span>Trips today</span><strong><MapPin size={15}/>{todayTrips.length + 18}</strong></div><div className="ops-metric"><span>On-time rate</span><strong className="text-green"><CircleCheck size={15}/>96.4%</strong></div><div className="ops-metric"><span>Fleet availability</span><strong><BusFront size={15}/>{data.vehicles.filter(v=>v.status==='Active').length}/{data.vehicles.length}</strong></div><div className="ops-metric"><span>Service alerts</span><Link to="/maintenance" className="alert-metric"><Wrench size={15}/>{data.maintenance.filter(m=>m.status!=='Completed').length} open</Link></div></section>
  </div>
}
function PlusIcon(){return <span className="plus-symbol">＋</span>}
