import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Plus, Search, Eye, Pencil, UserRound, Users, UserCheck, UserX, KeyRound, ShieldCheck, RefreshCw } from 'lucide-react'
import { request } from '../services/apiClient'
import './fleetWorkspace.css'

const emptyDriver={name:'',email:'',phone:'',licenseNumber:'',licenseExpiry:'',experienceYears:0}
const field=(label,key,form,setForm,opts={})=><label className="fw-field" key={key}><span>{label}{opts.required&&' *'}</span><input type={opts.type||'text'} required={!!opts.required} min={opts.min} value={form[key]??''} onChange={e=>setForm(old=>({...old,[key]:e.target.value}))} placeholder={opts.placeholder||''}/></label>
const initials=name=>String(name||'?').split(' ').slice(0,2).map(x=>x[0]).join('').toUpperCase()
function Avatar({name}){return <span className="fw-avatar">{initials(name)}</span>}
function Head({crumb,title,description,action}){return <><div className="fw-crumb"><Link to="/admin">Dashboard</Link><span>›</span><span>{crumb}</span></div><div className="fw-heading"><div><h1>{title}</h1><p>{description}</p></div>{action}</div></>}
function Alert({text}){return text?<p className="fw-alert" role="alert">{text}</p>:null}
function useRecords(path){const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[revision,setRevision]=useState(0);useEffect(()=>{let alive=true;setLoading(true);request(path).then(rows=>{if(alive){setItems(Array.isArray(rows)?rows:rows?.content||[]);setError('')}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[path,revision]);return {items,loading,error,setError,reload:()=>setRevision(n=>n+1)}}
function DriverNav(){return <div className="fw-tabs"><Link to="/admin/drivers">Driver list</Link><Link to="/admin/drivers/new">Create profile</Link><Link to="/admin/drivers/accounts">Driver accounts</Link></div>}
export function DriverList(){
 const {items,loading,error,setError,reload}=useRecords('/drivers');const [search,setSearch]=useState(''),[filter,setFilter]=useState('ALL'),[busy,setBusy]=useState(false);const navigate=useNavigate()
 const active=items.filter(x=>x.status==='AVAILABLE').length
 const shown=useMemo(()=>items.filter(x=>(filter==='ALL'||x.status===filter)&&[x.name,x.licenseNumber,x.phone,x.email].some(y=>String(y||'').toLowerCase().includes(search.toLowerCase()))),[items,filter,search])
 const change=async row=>{const next=row.status==='AVAILABLE'?'UNAVAILABLE':'AVAILABLE';if(!window.confirm('Set '+row.name+' to '+next+'?'))return;setBusy(true);try{await request('/drivers/'+row.id+'/status',{method:'PATCH',body:JSON.stringify({newStatus:next})});reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="fw-page"><Head crumb="Drivers" title="Drivers" description="Manage driver profiles, licences and availability." action={<Link className="fw-primary" to="/admin/drivers/new"><Plus size={16}/> Add Driver</Link>}/><DriverNav/><div className="fw-stats">{[[Users,'Total Drivers',items.length],[UserCheck,'Available Drivers',active],[UserX,'Unavailable Drivers',items.length-active]].map(([Icon,label,value])=><div className="fw-stat" key={label}><span><Icon size={19}/></span><div><strong>{value}</strong><small>{label}</small></div></div>)}</div><section className="fw-card"><div className="fw-toolbar"><div className="fw-search"><Search size={16}/><input aria-label="Search drivers" placeholder="Search drivers by name, license or phone..." value={search} onChange={e=>setSearch(e.target.value)}/></div><select aria-label="Filter drivers" value={filter} onChange={e=>setFilter(e.target.value)}><option value="ALL">All statuses</option><option value="AVAILABLE">Available</option><option value="UNAVAILABLE">Unavailable</option></select><button className="fw-icon-button" onClick={reload} title="Refresh"><RefreshCw size={15}/></button></div><Alert text={error}/>{loading?<p className="fw-empty">Loading drivers…</p>:<div className="fw-table-wrap"><table className="fw-table"><thead><tr><th>Driver</th><th>License No.</th><th>Phone</th><th>Status</th><th>Actions</th></tr></thead><tbody>{shown.map(row=><tr key={row.id}><td><div className="fw-person"><Avatar name={row.name}/><span><b>{row.name}</b><small>{row.email||'Driver profile'}</small></span></div></td><td>{row.licenseNumber}</td><td>{row.phone||'—'}</td><td><span className={'fw-badge '+(row.status==='AVAILABLE'?'fw-green':'fw-muted')}>{row.status==='AVAILABLE'?'Available':row.status||'Unavailable'}</span></td><td><div className="fw-actions"><button title="View driver" onClick={()=>navigate('/admin/drivers/'+row.id)}><Eye size={15}/> View</button><button title="Edit driver" onClick={()=>navigate('/admin/drivers/'+row.id+'/edit')}><Pencil size={15}/> Edit</button><button disabled={busy} onClick={()=>change(row)}>{row.status==='AVAILABLE'?'Set unavailable':'Set available'}</button></div></td></tr>)}</tbody></table>{shown.length===0&&<p className="fw-empty">No matching driver profiles.</p>}</div>}<div className="fw-table-footer">Showing {shown.length} of {items.length} drivers</div></section></div>
}
export function DriverForm(){
 const {id}=useParams();const edit=Boolean(id);const navigate=useNavigate();const [form,setForm]=useState(emptyDriver),[loading,setLoading]=useState(edit),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!edit)return;let alive=true;request('/drivers').then(rows=>{const row=rows.find(x=>String(x.id)===id);if(!row)throw Error('Driver profile not found.');if(alive)setForm(Object.fromEntries(Object.keys(emptyDriver).map(k=>[k,row[k]??emptyDriver[k]])))}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[id,edit])
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const payload={...form,experienceYears:Number(form.experienceYears)||0};await request(edit?'/drivers/'+id:'/drivers',{method:edit?'PUT':'POST',body:JSON.stringify(payload)});navigate('/admin/drivers')}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <div className="fw-page"><div className="fw-crumb"><Link to="/admin/drivers">Drivers</Link><span>›</span>{edit?'Edit Driver Profile':'Create Driver Profile'}</div><div className="fw-heading"><div><h1>{edit?'Edit Driver Profile':'Create Driver Profile'}</h1><p>Add the driver details supported by your Oracle driver profile.</p></div><Link className="fw-secondary" to="/admin/drivers"><ArrowLeft size={15}/> Back to drivers</Link></div><Alert text={error}/>{loading?<p>Loading profile…</p>:<form className="fw-form" onSubmit={save}><section className="fw-form-card"><h2><UserRound size={16}/> Personal information</h2><div className="fw-form-grid">{field('Full Name','name',form,setForm,{required:true,placeholder:'Enter full name'})}{field('Phone Number','phone',form,setForm,{placeholder:'07X XXX XXXX'})}{field('Email','email',form,setForm,{required:!edit,type:'email',placeholder:'driver@example.com'})}</div></section><section className="fw-form-card"><h2><ShieldCheck size={16}/> License information</h2><div className="fw-form-grid">{field('License Number','licenseNumber',form,setForm,{required:true})}{field('Expiry Date','licenseExpiry',form,setForm,{required:true,type:'date'})}{field('Years of Experience','experienceYears',form,setForm,{type:'number',min:0})}</div></section><div className="fw-form-footer"><Link className="fw-secondary" to="/admin/drivers">Cancel</Link><button className="fw-primary" disabled={busy}>{busy?'Saving…':edit?'Update Driver Profile':'Save Driver Profile'}</button></div></form>}<p className="fw-note">NIC, date of birth, document uploads and emergency contacts are not available in the current driver API, so they have not been added as nonfunctional fields.</p></div>
}
export function DriverDetail(){const {id}=useParams();const {items,loading,error}=useRecords('/drivers');const row=items.find(x=>String(x.id)===id);return <div className="fw-page"><Head crumb="Drivers / Profile" title="Driver profile" description="Driver information stored in Oracle." action={<Link className="fw-secondary" to="/admin/drivers">Back to list</Link>}/><Alert text={error}/>{loading?<p>Loading…</p>:row?<section className="fw-card fw-details"><div className="fw-person"><Avatar name={row.name}/><h2>{row.name}</h2></div>{[['Email',row.email],['Phone',row.phone],['License',row.licenseNumber],['License expiry',row.licenseExpiry],['Experience (years)',row.experienceYears],['Status',row.status]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value??'—'}</strong></div>)}<Link className="fw-primary" to={'/admin/drivers/'+id+'/edit'}><Pencil size={15}/> Edit profile</Link></section>:<p>Driver not found.</p>}</div>}
export function DriverAccounts(){
 const {items,loading,error,setError,reload}=useRecords('/admin/accounts/role/DRIVER');const {items:drivers}=useRecords('/drivers');const [search,setSearch]=useState(''),[busy,setBusy]=useState(false);const [form,setForm]=useState({driverId:'',username:'',password:''}),[creating,setCreating]=useState(false),[notice,setNotice]=useState('')
 const byId=Object.fromEntries(drivers.map(d=>[String(d.id),d]))
 const visible=items.filter(a=>[a.username,byId[String(a.driverId??a.linkedProfileId)]?.name].some(x=>String(x||'').toLowerCase().includes(search.toLowerCase())))
 const toggle=async a=>{const status=a.accountStatus==='ACTIVE'?'DISABLED':'ACTIVE';if(!window.confirm('Set '+a.username+' to '+status+'?'))return;setBusy(true);try{await request('/admin/accounts/'+a.id+'/status',{method:'PATCH',body:JSON.stringify({newStatus:status})});reload()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const create=async e=>{e.preventDefault();setBusy(true);setError('');try{await request('/admin/accounts/driver',{method:'POST',body:JSON.stringify({driverId:Number(form.driverId),username:form.username,password:form.password})});setCreating(false);setForm({driverId:'',username:'',password:''});setNotice('Driver login created. Share the initial password securely.');reload()}catch(err){setError(err.message)}finally{setBusy(false)}}
 return <div className="fw-page"><Head crumb="Drivers / Accounts" title="Driver Accounts" description="Create and manage login accounts for drivers only." action={<button className="fw-primary" onClick={()=>setCreating(v=>!v)}><Plus size={16}/> {creating?'Close form':'Create Driver Account'}</button>}/><DriverNav/><Alert text={error}/>{notice&&<p className="fw-notice" role="status">{notice}</p>}{creating&&<form className="fw-form-card fw-account-form" onSubmit={create}><h2><KeyRound size={16}/> Create driver login</h2><p>Select an existing driver profile to link the new login.</p><div className="fw-form-grid"><label className="fw-field"><span>Driver profile *</span><select required value={form.driverId} onChange={e=>setForm(v=>({...v,driverId:e.target.value}))}><option value="">Select a driver</option>{drivers.map(d=><option value={d.id} key={d.id}>{d.name} — {d.licenseNumber}</option>)}</select></label>{field('Username','username',form,setForm,{required:true})}{field('Initial password','password',form,setForm,{required:true,type:'password'})}</div><button className="fw-primary" disabled={busy||form.password.length<8}>{busy?'Creating…':'Create account'}</button><small>Passwords must contain at least 8 characters.</small></form>}<section className="fw-card"><div className="fw-toolbar"><div className="fw-search"><Search size={16}/><input placeholder="Search driver accounts..." value={search} onChange={e=>setSearch(e.target.value)}/></div><button className="fw-icon-button" onClick={reload}><RefreshCw size={15}/></button></div>{loading?<p className="fw-empty">Loading accounts…</p>:<div className="fw-table-wrap"><table className="fw-table"><thead><tr><th>Driver Name</th><th>Username</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map(a=><tr key={a.id}><td><div className="fw-person"><Avatar name={byId[String(a.driverId??a.linkedProfileId)]?.name||a.username}/><b>{byId[String(a.driverId??a.linkedProfileId)]?.name||'Driver account'}</b></div></td><td>{a.username}</td><td><span className="fw-badge fw-blue">Driver</span></td><td><span className={'fw-badge '+(a.accountStatus==='ACTIVE'?'fw-green':'fw-muted')}>{a.accountStatus}</span></td><td><button className="fw-secondary" disabled={busy} onClick={()=>toggle(a)}>{a.accountStatus==='ACTIVE'?'Disable':'Enable'}</button></td></tr>)}</tbody></table>{visible.length===0&&<p className="fw-empty">No driver accounts found.</p>}</div>}<div className="fw-table-footer">Showing {visible.length} of {items.length} driver accounts</div></section><p className="fw-note">Internal user account IDs are intentionally hidden. Only driver accounts are included in this view.</p></div>
}
export default DriverList
