import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, BusFront, CalendarDays, Check, ChevronDown, Clock3, MapPin, Menu, MoveRight, Search, ShieldCheck, Sparkles, Star, TicketCheck, UsersRound, X } from 'lucide-react'
import { useAppData } from '../services/useAppData'
import { formatLkr, formatDate } from '../services/formatters'

const destinations = [
  { name: 'Colombo', region: 'Western Province', img: 'photo-1566552881560-0be862a7c445' },
  { name: 'Kandy', region: 'Hill Country', img: 'photo-1544735716-392fe2489ffa', badge: 'MOST LOVED' },
  { name: 'Galle', region: 'Southern Coast', img: 'photo-1533105079780-92b9be482077' },
  { name: 'Ella', region: 'Highlands', img: 'photo-1500530855697-b586d89ba3ee', badge: 'SCENIC ROUTE' },
  { name: 'Jaffna', region: 'Northern Province', img: 'photo-1516026672322-bc52d61a55d5' },
]
const assetUrl = id => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=82`
const testimonials = [
  { text: 'The booking was effortless and the ride to Kandy was so comfortable. I loved knowing exactly where my bus was.', name: 'Nadeesha P.', route: 'Colombo → Kandy', initials: 'NP' },
  { text: 'A much easier way to plan weekend trips. Clear timings, friendly service, and no surprises along the way.', name: 'Tharindu W.', route: 'Colombo → Galle', initials: 'TW' },
  { text: 'The journey through the hills was beautiful. Having the ticket ready on my phone made everything simple.', name: 'Kavindi R.', route: 'Kandy → Ella', initials: 'KR' },
]

export default function Landing() {
  const { data } = useAppData()
  const navigate = useNavigate()
  const [menu, setMenu] = useState(false)
  const [from, setFrom] = useState('Colombo')
  const [to, setTo] = useState('')
  const [date, setDate] = useState('')
  const [passengers, setPassengers] = useState('1')
  const [faq, setFaq] = useState(0)
  const cities = [...new Set(data.routes.flatMap(route => [route.origin, route.destination]))]
  const trips = data.trips.filter(trip => trip.status === 'Scheduled').slice(0, 3)
  const search = event => { event.preventDefault(); const params = new URLSearchParams({ from, to, date, passengers }); navigate(`/passenger/search?${params}`) }
  return <div className="public-site">
    <header className="public-header"><Link to="/" className="public-logo"><span><BusFront size={22}/></span><b>smart<span>move</span></b></Link><button className="public-menu-btn" onClick={() => setMenu(!menu)} aria-label="Toggle navigation">{menu ? <X size={20}/> : <Menu size={20}/>}</button><nav className={`public-nav ${menu ? 'open' : ''}`}><a href="#home" onClick={() => setMenu(false)}>Home</a><a href="#routes" onClick={() => setMenu(false)}>Routes</a><a href="#destinations" onClick={() => setMenu(false)}>Destinations</a><a href="#about" onClick={() => setMenu(false)}>About</a><span className="public-nav-mobile"><Link to="/login">Log in</Link><Link className="public-nav-signup" to="/register">Sign up <ArrowUpRight size={15}/></Link></span></nav><div className="public-auth-links"><Link to="/login">Log in</Link><Link className="public-signup" to="/register">Sign up <ArrowUpRight size={15}/></Link></div></header>
    <main>
      <section className="landing-hero" id="home"><div className="hero-photo" role="img" aria-label="Scenic Sri Lankan hill country and winding road"/><div className="hero-shade"/><div className="hero-copy"><span className="hero-kicker"><i/> THE ISLAND IS YOURS TO EXPLORE</span><h1>Your journey,<br/><em>made simple.</em></h1><p>See more of Sri Lanka. We’ll take you there with comfort, confidence and a little more room to enjoy the view.</p><div className="hero-promise"><span><Check size={15}/> Thoughtful journeys</span><span><Check size={15}/> Simple booking</span><span><Check size={15}/> Local at heart</span></div></div><div className="hero-side-note"><span>06° 55′ N</span><i/> <span>79° 51′ E</span><small>COLOMBO, SRI LANKA</small></div>
        <form className="trip-search-card" onSubmit={search}><div className="search-card-title"><div><span className="search-card-eyebrow">WHERE TO NEXT?</span><strong>Find your ride</strong></div><span className="search-demo-label"><span/> Live routes</span></div><div className="search-fields"><label className="search-field"><span>FROM</span><div><MapPin size={16}/><select value={from} onChange={e=>setFrom(e.target.value)} aria-label="From">{cities.map(city=><option key={city}>{city}</option>)}</select></div></label><div className="search-swap"><MoveRight size={17}/></div><label className="search-field"><span>TO</span><div><MapPin size={16}/><select value={to} onChange={e=>setTo(e.target.value)} required aria-label="To"><option value="">Choose destination</option>{cities.filter(city=>city!==from).map(city=><option key={city}>{city}</option>)}</select></div></label><label className="search-field"><span>TRAVEL DATE</span><div><CalendarDays size={16}/><input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)} aria-label="Travel date"/></div></label><label className="search-field search-passengers"><span>PASSENGERS</span><div><UsersRound size={16}/><select value={passengers} onChange={e=>setPassengers(e.target.value)} aria-label="Passengers">{[1,2,3,4,5,6].map(count=><option key={count} value={count}>{count} {count===1?'Passenger':'Passengers'}</option>)}</select></div></label></div><div className="search-submit-row"><span>Easy booking, no account needed to search.</span><button className="landing-search-btn" type="submit">Search trips <ArrowRight size={17}/></button></div></form>
        <div className="hero-scroll">SCROLL TO EXPLORE <span/></div>
      </section>
      <section className="trust-strip"><div className="trust-item"><span><Star size={15} fill="currentColor"/></span><b>4.9/5</b><small>traveller-loved journeys</small></div><i/><div className="trust-item"><b>Island-wide</b><small>routes made for discovery</small></div><i/><div className="trust-item"><b>Easy from start to seat</b><small>browse, book, and go</small></div><div className="trust-note">Your next good story starts on the road.</div></section>
      <section className="section destinations-section" id="destinations"><div className="section-heading"><div><span className="section-kicker">A LITTLE INSPIRATION</span><h2>Somewhere wonderful<br/>is just a ride away.</h2></div><Link to="/passenger/search" className="underlined-link">Explore every route <ArrowRight size={16}/></Link></div><div className="destination-grid">{destinations.map((destination,index)=><button type="button" className={`destination-card destination-${index+1}`} key={destination.name} onClick={()=>navigate(`/passenger/search?${new URLSearchParams({from:destination.name==='Colombo'?'Kandy':'Colombo',to:destination.name})}`)}><img src={assetUrl(destination.img)} alt={`${destination.name}, Sri Lanka`} loading="lazy" onError={event=>{event.currentTarget.style.display='none'}}/><div className="destination-gradient"/><span className="destination-number">0{index+1}</span>{destination.badge&&<span className="destination-badge">{destination.badge}</span>}<span className="destination-info"><small>{destination.region}</small><strong>{destination.name}</strong></span><span className="destination-arrow"><ArrowUpRight size={17}/></span></button>)}</div></section>
      <section className="section trips-section" id="routes"><div className="section-heading"><div><span className="section-kicker">PICK YOUR NEXT DEPARTURE</span><h2>Good routes. Good reasons<br/>to get going.</h2></div><Link to="/passenger/search" className="underlined-link">Browse all trips <ArrowRight size={16}/></Link></div><div className="featured-trips">{trips.map((trip,index)=>{const route=data.routes.find(item=>item.id===trip.routeId);const vehicle=data.vehicles.find(item=>item.id===trip.vehicleId);const booked=data.bookings.filter(b=>b.tripId===trip.id&&b.status!=='Cancelled').reduce((sum,b)=>sum+Number(b.seats||0),0);return <article className="featured-trip" key={trip.id}><div className={`trip-art trip-art-${index+1}`}><span>{index===0?'HIGHLAND EXPRESS':index===1?'COASTAL LINE':'HILL COUNTRY'}</span><BusFront size={49}/><small>{vehicle?.type||'Comfort coach'}</small></div><div className="featured-trip-body"><span className="trip-route-line">{route?.origin}<ArrowRight size={14}/>{route?.destination}</span><div className="trip-meta"><span><Clock3 size={14}/>{trip.departure} – {trip.arrival}</span><span><CalendarDays size={14}/>{formatDate(trip.date)}</span></div><div className="trip-meta"><span><BusFront size={14}/>{vehicle?.name}</span><span>{Math.max(0,(trip.seats||0)-booked)} seats left</span></div><div className="featured-trip-bottom"><span>from <b>{formatLkr(route?.fare)}</b><small> / seat</small></span><Link to={`/passenger/trip/${trip.id}`} aria-label={`View trip to ${route?.destination}`}><ArrowRight size={17}/></Link></div></div></article>})}</div></section>
      <section className="how-section" id="about"><div className="how-visual"><div className="how-img"><img src={assetUrl('photo-1500534623283-312aade485b7')} alt="Sunlit Sri Lankan countryside" loading="lazy" onError={event=>{event.currentTarget.style.display='none'}}/><div className="how-img-overlay"/></div><div className="how-stamp"><Sparkles size={16}/><span>Less planning.<br/>More looking out<br/>the window.</span></div><div className="how-caption">THE LONG WAY CAN BE THE BEST WAY.</div></div><div className="how-content"><span className="section-kicker">THOUGHTFULLY SIMPLE</span><h2>Good travel<br/>should feel easy.</h2><p className="how-intro">From the first search to the last stop, we keep the details clear so you can focus on the reason you’re going.</p><div className="steps"><div className="step"><span>01</span><div><strong>Find your way</strong><small>Choose your destination, date and the ride that fits.</small></div><Search size={18}/></div><div className="step"><span>02</span><div><strong>Save your seat</strong><small>Book simply and keep your journey details close.</small></div><TicketCheck size={18}/></div><div className="step"><span>03</span><div><strong>Enjoy the ride</strong><small>Meet us at the stop. Sri Lanka is waiting outside.</small></div><MapPin size={18}/></div></div></div></section>
      <section className="why-section"><div className="why-head"><span className="section-kicker">THE SMARTMOVE DIFFERENCE</span><h2>Travel that feels<br/><em>a little more human.</em></h2><p>We’re not just getting you there. We’re making the way there worth remembering.</p></div><div className="why-grid"><article><span className="why-icon"><ShieldCheck size={20}/></span><strong>Comfort you can count on</strong><p>Well-kept vehicles and considerate service make the miles feel lighter.</p></article><article><span className="why-icon"><MapPin size={20}/></span><strong>Made for this island</strong><p>Local routes connect the places you love with the places you’re about to.</p></article><article><span className="why-icon"><TicketCheck size={20}/></span><strong>Simple all the way through</strong><p>Clear schedules and a smoother booking flow, with no unnecessary fuss.</p></article><article><span className="why-icon"><UsersRound size={20}/></span><strong>People first, always</strong><p>Thoughtful support for everyday commutes and once-in-a-while adventures.</p></article></div></section>
      <section className="testimonial-section"><div className="section-heading"><div><span className="section-kicker">KIND WORDS FROM THE ROAD</span><h2>It’s the little things<br/>that make a journey.</h2></div><div className="demo-example-note">Demo example testimonials</div></div><div className="testimonial-grid">{testimonials.map(testimonial=><article className="testimonial-card" key={testimonial.initials}><div className="testimonial-stars">★★★★★ <span>5.0</span></div><p>“{testimonial.text}”</p><div className="testimonial-person"><span>{testimonial.initials}</span><div><strong>{testimonial.name}</strong><small>{testimonial.route}</small></div><span className="quote-mark">”</span></div></article>)}</div></section>
      <section className="notice-section"><div className="notice-deco"><MegaphoneIcon/></div><div className="notice-copy"><span className="section-kicker">A NOTE FROM OUR TEAM</span><h2>A little heads-up for the road.</h2><p>Keep an eye on service updates and route notices before you set out.</p></div><div className="notice-list">{data.announcements.filter(item=>item.status==='Published').slice(0,2).map(item=><div key={item.id}><span className="notice-date">{formatDate(item.date)}</span><strong>{item.title}</strong><small>{item.message}</small></div>)}</div><Link to="/passenger/announcements" className="notice-link">All travel notices <ArrowRight size={15}/></Link></section>
      <section className="faq-section" id="faq"><div><span className="section-kicker">GOOD TO KNOW</span><h2>A few things<br/>you might wonder.</h2><p>Still curious? <Link to="/login">Our team is happy to help.</Link></p></div><div className="faq-list">{[{q:'Can I search trips before creating an account?',a:'Of course. Search, compare routes, schedules and fares first. You only need a passenger account when you are ready to reserve seats.'},{q:'How do I get my ticket after booking?',a:'Your booking appears in My Bookings and My Tickets in the passenger portal. This is a demo experience; ticket delivery and validation require a connected backend.'},{q:'Can I change or cancel my trip?',a:'Demo bookings can be cancelled from My Bookings before the trip is underway. Real-world changes depend on operator policy and future backend support.'},{q:'Are online payments available?',a:'No. Payment records shown in the demo are administrative examples only. No card data is collected and no payments are processed.'}].map((item,index)=><div className={`faq-item ${faq===index?'expanded':''}`} key={item.q}><button onClick={()=>setFaq(faq===index?-1:index)} aria-expanded={faq===index}><span>{item.q}</span><ChevronDown size={18}/></button>{faq===index&&<p>{item.a}</p>}</div>)}</div></section>
      <section className="final-cta"><div className="cta-orb"/><span className="section-kicker">THE ISLAND IS CALLING</span><h2>Make room for<br/><em>the journey.</em></h2><p>Pick a place. We’ll help you get there.</p><div><Link className="cta-white-btn" to="/passenger/search">Find your trip <ArrowRight size={16}/></Link><Link className="cta-quiet-link" to="/register">Create your free account <ArrowUpRight size={15}/></Link></div><span className="cta-bottom-note"><i/> YOUR NEXT CHAPTER STARTS HERE</span></section>
    </main>
    <footer className="public-footer"><div className="footer-main"><div className="footer-brand-col"><Link to="/" className="public-logo footer-logo"><span><BusFront size={22}/></span><b>smart<span>move</span></b></Link><p>More than a ride. A better way to see the island.</p><div className="footer-socials"><a href="#home" aria-label="Facebook">f</a><a href="#home" aria-label="Instagram">◎</a><a href="#home" aria-label="LinkedIn">in</a></div></div><div className="footer-col"><strong>EXPLORE</strong><a href="#destinations">Destinations</a><a href="#routes">Popular routes</a><Link to="/passenger/search">Find a trip</Link><a href="#about">Our approach</a></div><div className="footer-col"><strong>YOUR JOURNEY</strong><Link to="/login">Passenger login</Link><Link to="/register">Create an account</Link><Link to="/login">Driver portal</Link><Link to="/login">Admin demo</Link></div><div className="footer-col"><strong>HERE TO HELP</strong><a href="#faq">Travel questions</a><a href="mailto:hello@smartmove.lk">hello@smartmove.lk</a><span>Colombo, Sri Lanka</span><span>Daily, 6:00 am – 8:00 pm</span></div><div className="footer-newsletter"><strong>A little more inspiration?</strong><p>Sign in to hear about routes, updates and places worth discovering.</p><Link to="/register">Join the journey <ArrowRight size={15}/></Link></div></div><div className="footer-bottom"><span>© 2026 SmartMove Transport Solutions. Made for the journey.</span><span><Link to="/login">Demo experience</Link> · Privacy · Terms</span></div><p className="public-demo-disclaimer">Passenger stories, service claims and route availability shown here are illustrative demo content. Booking, payment, authentication and notification services are not connected.</p></footer>
  </div>
}
function MegaphoneIcon(){return <span><BusFront size={23}/></span>}
