import { useState } from 'react'
import { Link, Navigate, useNavigate, useSearchParams } from 'react-router-dom'
import { ArrowLeft, ArrowRight, BusFront, Check, Eye, EyeOff, UserPlus } from 'lucide-react'
import { useAppData } from '../services/useAppData'

export default function Register() {
  const { session, data, addRecord, signIn } = useAppData()
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const [values, setValues] = useState({name:'',email:'',phone:'',password:'',confirm:''})
  const [show, setShow] = useState(false)
  const [error, setError] = useState('')
  const [busy,setBusy] = useState(false)
  const next = params.get('next') || '/passenger'
  if (session) return <Navigate to={session.role==='admin'?'/admin':session.role==='driver'?'/driver':'/passenger'} replace/>
  const change=event=>setValues({...values,[event.target.name]:event.target.value})
  const submit=event=>{event.preventDefault();setError('');if(values.name.trim().length<2)return setError('Enter your full name.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email))return setError('Enter a valid email address.');if(!/^\+?[0-9 ()-]{7,18}$/.test(values.phone))return setError('Enter a valid phone number.');if(values.password.length<8)return setError('For this demo form, use at least 8 characters. Passwords are not stored.');if(values.password!==values.confirm)return setError('Your passwords do not match.');if(data.passengers.some(person=>person.email.toLowerCase()===values.email.trim().toLowerCase()))return setError('An account with this email already exists. Try signing in.');setBusy(true);const id=`PS-${Date.now().toString().slice(-6)}`;addRecord('passengers',{id,name:values.name.trim(),email:values.email.trim(),phone:values.phone.trim(),city:'Colombo',joined:new Date().toISOString().slice(0,10),trips:0});signIn('passenger',id);navigate(next,{replace:true})}
  return <main className="auth-page"><aside className="auth-art"><div className="auth-art-image"/><Link className="auth-brand" to="/"><span><BusFront size={21}/></span>smart<span>move</span></Link><div className="auth-art-copy"><span>A SEAT FOR EVERY STORY</span><h1>More island.<br/>More moments.<br/><em>Your way.</em></h1><p>Create an account and keep your journeys together.</p></div><div className="auth-art-foot">PASSENGER MEMBERSHIP · DEMO ONLY</div></aside><section className="auth-main"><Link className="auth-back" to="/"><ArrowLeft size={15}/> Back to SmartMove</Link><div className="auth-box register-box"><div className="auth-mobile-logo"><span><BusFront size={20}/></span> smartmove</div><span className="auth-kicker">A BETTER WAY TO GO</span><h2>Let’s make it<br/>official-ish.</h2><p className="auth-subtitle">Create a passenger profile to save a seat.</p><div className="account-rule"><Check size={16}/><span>Passenger profiles can self-register. Driver and admin access is provisioned separately.</span></div><form className="auth-form" onSubmit={submit}><label>Full name<input name="name" autoComplete="name" placeholder="Your name" value={values.name} onChange={change} required/></label><label>Email address<input type="email" name="email" autoComplete="email" placeholder="you@example.com" value={values.email} onChange={change} required/></label><label>Phone number<input type="tel" name="phone" autoComplete="tel" placeholder="+94 77 123 4567" value={values.phone} onChange={change} required/></label><label>Password<div className="password-field"><input type={show?'text':'password'} name="password" autoComplete="new-password" placeholder="At least 8 characters" value={values.password} onChange={change} required minLength={8}/><button type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><label>Confirm password<input type={show?'text':'password'} name="confirm" autoComplete="new-password" placeholder="Type it once more" value={values.confirm} onChange={change} required/></label>{error&&<div className="auth-error" role="alert">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?'Creating profile…':<>Create passenger account <ArrowRight size={16}/></>}</button></form><div className="demo-disclaimer"><UserPlus size={16}/><p><strong>Demo profile only.</strong> Passwords are not stored or verified. Future accounts require secure backend registration and password hashing.</p></div><div className="auth-signup">Already have a profile? <Link to={`/login${params.get('next')?`?next=${encodeURIComponent(params.get('next'))}`:''}`}>Sign in</Link></div></div><footer className="auth-footer">© 2026 SmartMove Transport Solutions <span>Demo experience · No password persistence</span></footer></section></main>
}
