import { isApiMode } from '../services/apiClient'
import ApiReports from '../components/ApiReports'
import { Link } from 'react-router-dom'
import { Download, ChartNoAxesCombined, TrendingUp, Route, Users } from 'lucide-react'
import { useAppData } from '../services/useAppData'
import { formatLkr } from '../services/formatters'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'

function DemoReports() {
  const { data } = useAppData()
  const routeRows = data.routes.map(route => ({ name: route.origin.split(' ')[0] + '–' + route.destination.split(' ')[0], trips: data.trips.filter(trip => trip.routeId === route.id).length * 11 + 18, revenue: data.bookings.filter(booking => data.trips.some(trip => trip.id === booking.tripId && trip.routeId === route.id) && booking.status !== 'Cancelled').reduce((total, booking) => total + booking.amount, 0) }))
  const revenue = data.payments.filter(payment => payment.status === 'Paid').reduce((sum, payment) => sum + payment.amount, 0)
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">SMARTMOVE OPERATIONS</div><h1>Reports</h1><p>Insights into network performance and service delivery.</p></div><button className="button button-primary" onClick={() => window.print()}><Download size={16}/> Export report</button></div><div className="report-banner"><div className="report-banner-icon"><ChartNoAxesCombined size={22}/></div><div><strong>October operations summary</strong><p>Performance snapshot based on locally stored demo records. Trend charts include illustrative sample metrics.</p></div><span className="report-period">OCT 2025</span></div><div className="mini-stats"><div className="mini-stat"><span>Recorded payments</span><strong>{formatLkr(revenue)}</strong><small>Administrative records only</small></div><div className="mini-stat"><span>Bookings</span><strong>{data.bookings.length}</strong><small>All current statuses</small></div><div className="mini-stat"><span>Passenger profiles</span><strong>{data.passengers.length}</strong><small>Across {new Set(data.passengers.map(item=>item.city)).size} cities</small></div></div><section className="panel report-chart-panel"><div className="panel-header"><div><h2>Route activity</h2><p>Illustrative weekly trip volume by route</p></div><span className="chart-legend"><i/> Trips</span></div><div className="report-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={routeRows} margin={{ top: 16, right: 20, left: 0, bottom: 0 }}><CartesianGrid vertical={false} stroke="#edf0eb"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 12 }} dy={10}/><YAxis axisLine={false} tickLine={false} tick={{ fill: '#879187', fontSize: 11 }}/><Tooltip contentStyle={{ border: '1px solid #e8ece6', borderRadius: 10 }}/><Bar dataKey="trips" fill="#779681" radius={[5,5,1,1]} maxBarSize={48}/></BarChart></ResponsiveContainer></div></section><div className="report-cards"><Link to="/routes" className="report-shortcut"><span><Route size={19}/></span><div><strong>Route performance</strong><small>View routes, distance and fares</small></div><TrendingUp size={17}/></Link><Link to="/passengers" className="report-shortcut"><span><Users size={19}/></span><div><strong>Passenger insights</strong><small>Explore your passenger directory</small></div><TrendingUp size={17}/></Link></div><p className="demo-footnote">Reports are generated from browser demo data. A production reporting service and verified analytics are not connected.</p></div>
}

export default function Reports() { return isApiMode() ? <ApiReports /> : <DemoReports /> }
