import { useMemo, useState } from 'react'
import { BusFront, CalendarDays, Check, Clock3, Plus, Route, Search, ShieldCheck, Users, X } from 'lucide-react'
import { useAppData } from '../../services/useAppData'
import { formatDate } from '../../services/formatters'
import { supportedPlaces } from '../../services/placeCatalogue'

const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun']
const minutes=time=>{const [h,m]=String(time||'00:00').split(':').map(Number);return h*60+m}
const hasOverlap=(data,date,start,end,vehicleId,driverId)=>data.trips.some(trip=>trip.date===date&&!['Cancelled','Completed'].includes(trip.status)&&(trip.vehicleId===vehicleId||trip.driverId===driverId)&&minutes(start)<(minutes(trip.arrival)<minutes(trip.departure)?minutes(trip.arrival)+1440:minutes(trip.arrival))&&minutes(trip.departure)<end)

export default function StaffTransportAdmin(){
  const {data,addRecord,updateRecord}=useAppData()
  const [showForm,setShowForm]=useState(false)
  const [notice,setNotice]=useState('')
  const [error,setError]=useState('')
  const [query,setQuery]=useState('')
  const [companyId,setCompanyId]=useState(data.companies[0]?.id||'')
  const [placeNames,setPlaceNames]=useState('Piliyandala, Maharagama, Nugegoda, Orion City, Colombo')
  const [operatingDays,setOperatingDays]=useState(['Mon','Tue','Wed','Thu','Fri'])
  const [vehicleId,setVehicleId]=useState('')
  const [driverId,setDriverId]=useState('')
  const [addCompany,setAddCompany]=useState(false)
  const [newCompanyName,setNewCompanyName]=useState('')
  const [newWorkplace,setNewWorkplace]=useState('')
  const [travelDate,setTravelDate]=useState('')
  const [departure,setDeparture]=useState('07:00')
  const [arrival,setArrival]=useState('08:15')
  const routes=useMemo(()=>data.staffRoutes||[],[data.staffRoutes])
  const filtered=useMemo(()=>routes.filter(route=>[route.name,route.companyName,route.origin,route.destination].some(value=>String(value||'').toLowerCase().includes(query.toLowerCase()))),[routes,query])
  const routeStops=placeNames.split(',').map(name=>supportedPlaces.find(place=>place.name.toLowerCase()===name.trim().toLowerCase())).filter(Boolean)
  const createRoute=event=>{
    event.preventDefault();setError('');setNotice('')
    const company=data.companies.find(item=>item.id===companyId),vehicle=data.vehicles.find(item=>item.id===vehicleId),driver=data.drivers.find(item=>item.id===driverId),driverAccount=data.users.find(user=>user.linkedProfileId===driverId&&user.role==='DRIVER')
    if(!company||!vehicle||!driver)return setError('Choose a company, vehicle and driver.')
    if(routeStops.length<2)return setError('Enter at least two supported stop names separated by commas.')
    if(operatingDays.length===0)return setError('Select at least one operating day.')
    if(vehicle.status!=='Active')return setError('Only active vehicles may serve a staff route.')
    if(driver.status!=='On duty')return setError('Only on-duty drivers may serve a staff route.')
    if(driverAccount&&driverAccount.accountStatus!=='ACTIVE')return setError('The selected driver account is disabled.')
    if(hasOverlap(data,travelDate,departure,minutes(arrival),vehicleId,driverId))return setError('That vehicle or driver has an overlapping trip assignment on the selected date.')
    const id=`ST-${crypto.randomUUID().slice(0,8).toUpperCase()}`,routeId=`RT-${id}`
    const stops=routeStops.map((place,index)=>({stopOrder:index+1,name:place.name,latitude:place.latitude,longitude:place.longitude,scheduledTime:index===0?departure:index===routeStops.length-1?arrival:''}))
    const route={id,routeId,serviceType:'STAFF',companyId,companyName:company.name,name:`${stops[0].name} → ${stops.at(-1).name}`,origin:stops[0].name,destination:stops.at(-1).name,stops,operatingDays,assignedVehicleId:vehicleId,assignedDriverId:driverId,distance:0,duration:'Demo schedule',fare:0,status:'Active'}
    addRecord('staffRoutes',route)
    addRecord('trips',{id:`TR-${crypto.randomUUID().slice(0,8).toUpperCase()}`,routeId,vehicleId,driverId,date:travelDate,departure,arrival,seats:vehicle.capacity,status:'Scheduled',serviceType:'STAFF',companyId,companyName:company.name})
    setNotice(`${route.name} added for ${company.name}; one demo trip was scheduled for ${formatDate(travelDate)}.`)
    setPlaceNames('');setShowForm(false)
  }
  const toggleEligibility=employee=>{updateRecord('employees',employee.id,{eligible:!employee.eligible});setNotice(`Employee ${employee.employeeCode} ${employee.eligible?'removed from':'added to'} the demo eligible roster.`)}
  const saveCompany=()=>{
    if(newCompanyName.trim().length<2||newWorkplace.trim().length<2)return setError('Enter a company name and workplace destination.')
    if(data.companies.some(company=>company.name.toLowerCase()===newCompanyName.trim().toLowerCase()))return setError('That demo company already exists.')
    const id=`CO-${crypto.randomUUID().slice(0,8).toUpperCase()}`
    addRecord('companies',{id,name:newCompanyName.trim(),workplace:newWorkplace.trim(),employeeIds:[]})
    setCompanyId(id);setNewCompanyName('');setNewWorkplace('');setAddCompany(false);setNotice('Demo company and workplace added to the shared operations data.')
  }
  return <div className="page-content"><div className="page-heading"><div><div className="eyebrow">TRANSPORT SERVICES · STAFF</div><h1>Staff transportation</h1><p>Manage company shuttles, roster eligibility, vehicle assignments and requests.</p></div><button className="button button-primary" onClick={()=>{setShowForm(!showForm);setError('')}}><Plus size={16}/>{showForm?'Close':'Create staff route'}</button></div><div className="custom-admin-banner"><ShieldCheck size={16}/><span>Dedicated company routes are separate from commuter services. Demo eligibility is an interface preview; Spring Boot must enforce employee access.</span></div>{notice&&<div className="notice-banner" role="status"><span>{notice}</span><button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={16}/></button></div>}
  {showForm&&<form className="staff-route-form portal-panel" onSubmit={createRoute}><div className="portal-panel-head"><div><h2>New company shuttle</h2><p>Choose an employer route and set a sample upcoming trip.</p></div></div><div className="staff-form-grid"><label>Company<select value={companyId} onChange={event=>setCompanyId(event.target.value)}>{data.companies.map(company=><option key={company.id} value={company.id}>{company.name} · {company.workplace}</option>)}</select></label><button type="button" className="button button-quiet add-company-toggle" onClick={()=>setAddCompany(value=>!value)}>＋ Define company/workplace</button>{addCompany&&<div className="new-company-fields"><label>Company name<input value={newCompanyName} onChange={event=>setNewCompanyName(event.target.value)}/></label><label>Workplace destination<input value={newWorkplace} onChange={event=>setNewWorkplace(event.target.value)}/></label><button type="button" className="button button-outline" onClick={saveCompany}>Add company</button></div>}<label className="staff-stops-field">Stops in travel order<input value={placeNames} onChange={event=>setPlaceNames(event.target.value)} placeholder="Use supported place names, comma separated"/><small>Supported names: {supportedPlaces.slice(0,10).map(place=>place.name).join(', ')}…</small></label><label>Operating days<div className="staff-days">{DAYS.map(day=><button type="button" key={day} className={operatingDays.includes(day)?'selected':''} onClick={()=>setOperatingDays(days=>days.includes(day)?days.filter(item=>item!==day):[...days,day])}>{day}</button>)}</div></label><label>First demo trip date<input type="date" min={new Date().toISOString().slice(0,10)} value={travelDate} onChange={event=>setTravelDate(event.target.value)} required/></label><label>Departure<input type="time" value={departure} onChange={event=>setDeparture(event.target.value)} required/></label><label>Destination arrival<input type="time" value={arrival} onChange={event=>setArrival(event.target.value)} required/></label><label>Vehicle<select value={vehicleId} onChange={event=>setVehicleId(event.target.value)} required><option value="">Select active vehicle</option>{data.vehicles.map(vehicle=><option key={vehicle.id} value={vehicle.id} disabled={vehicle.status!=='Active'}>{vehicle.plate} · {vehicle.name} ({vehicle.capacity} seats · {vehicle.status})</option>)}</select></label><label>Driver<select value={driverId} onChange={event=>setDriverId(event.target.value)} required><option value="">Select on-duty driver</option>{data.drivers.map(driver=><option key={driver.id} value={driver.id} disabled={driver.status!=='On duty'}>{driver.name} · {driver.status}</option>)}</select></label></div>{error&&<p className="form-error-text" role="alert">{error}</p>}<button className="button button-primary"><Check size={15}/> Create staff route and first trip</button></form>}
  <div className="staff-admin-grid"><section className="portal-panel"><div className="portal-panel-head"><div><h2>Company staff routes</h2><p>{routes.length} dedicated route(s)</p></div><label className="staff-search"><Search size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search company or stop"/></label></div>{filtered.length?<div className="staff-route-list">{filtered.map(route=>{const trip=data.trips.find(item=>item.routeId===route.routeId);const vehicle=data.vehicles.find(item=>item.id===route.assignedVehicleId),driver=data.drivers.find(item=>item.id===route.assignedDriverId);return <article className="staff-route-admin-card" key={route.id}><div className="staff-route-admin-title"><span className="staff-route-icon"><BusFront size={17}/></span><div><strong>{route.name}</strong><small>{route.companyName} · {route.operatingDays?.join(' / ')}</small></div><span className="staff-service-badge">STAFF</span></div><div className="staff-route-stops">{route.stops?.map(stop=><span key={stop.stopOrder}><i/>{stop.name}{stop.scheduledTime&&<small>{stop.scheduledTime}</small>}</span>)}</div><div className="staff-route-meta"><span><BusFront size={13}/>{vehicle?.plate||'Vehicle not assigned'}</span><span><Users size={13}/>{driver?.name||'Driver not assigned'}</span><span><CalendarDays size={13}/>{trip?formatDate(trip.date):'No trip date'}</span><span><Clock3 size={13}/>{trip?`${trip.departure}–${trip.arrival}`:'—'}</span></div></article>})}</div>:<div className="portal-empty compact"><span><Route size={20}/></span><strong>No matching staff routes</strong><p>Create a route or adjust the search.</p></div>}</section>
  <section className="portal-panel"><div className="portal-panel-head"><div><h2>Employee eligibility</h2><p>Demo rosters, separated by company.</p></div></div>{data.employees.length?<div className="employee-eligibility-list">{data.employees.map(employee=>{const company=data.companies.find(item=>item.id===employee.companyId),passenger=data.passengers.find(item=>item.id===employee.passengerId);return <article key={employee.id}><span className="employee-avatar">{passenger?.name?.split(' ').map(part=>part[0]).slice(0,2).join('')||'EM'}</span><div><strong>{passenger?.name||employee.employeeCode}</strong><small>{company?.name} · {employee.employeeCode}</small></div><button type="button" className={`eligibility-toggle ${employee.eligible?'eligible':'ineligible'}`} onClick={()=>toggleEligibility(employee)}>{employee.eligible?'Eligible':'Not eligible'}</button></article>})}</div>:<div className="portal-empty compact"><span><Users size={20}/></span><strong>No demo employee roster</strong><p>Employee profiles will be managed from the backend.</p></div>}</section></div>
  <section className="portal-panel staff-bookings-admin"><div className="portal-panel-head"><div><h2>Staff reservations & active trips</h2><p>Employee reservations and current staff-service assignments.</p></div></div><div className="staff-admin-grid"><div><strong className="staff-subheading">RESERVATIONS</strong>{(data.staffBookings||[]).length?(data.staffBookings||[]).map(booking=><div className="staff-mini-record" key={booking.id}><span>{booking.routeName||booking.tripId}</span><small>{booking.seats} seat(s) · {booking.status} · {booking.employeeId}</small></div>):<div className="empty-small">No staff reservations yet.</div>}</div><div><strong className="staff-subheading">ACTIVE STAFF TRIPS</strong>{data.trips.filter(trip=>trip.serviceType==='STAFF'&&trip.status==='In progress').length?data.trips.filter(trip=>trip.serviceType==='STAFF'&&trip.status==='In progress').map(trip=><div className="staff-mini-record" key={trip.id}><span>{trip.companyName} · {trip.id}</span><small>{trip.date} · {trip.departure} · {trip.vehicleId}</small></div>):<div className="empty-small">No staff service is currently marked in progress.</div>}</div></div></section><p className="portal-demo-caption">Company, employee, schedule and reservation data uses shared local demo state. Availability and access rules are not authoritative.</p></div>
}
